### ISSUE TITLE
切换错误  next()

### ISSUE THREAD

**Issue by liuhangbiao** [DhyanaChina/simpler-paper#74]
server listening on port: 3001
C:\xxxxxxxxxxxxx\AppData\Roaming\npm\node_modules\simpler-paper\node_modules\serve-static\index.js:121
      next()
      ^

TypeError: next is not a function
    at SendStream.error (C:\xxxxxxxxxxxxx\AppData\Roaming\npm\node_modules\simpler-paper\node_modules\serve-static\index.js:121:7)
    at emitOne (events.js:96:13)
    at SendStream.emit (events.js:188:7)
    at SendStream.error (C:\xxxxxxxxxxxxx\AppData\Roaming\npm\node_modules\simpler-paper\node_modules\send\index.js:270:17)
    at SendStream.onStatError (C:\xxxxxxxxxxxxx\AppData\Roaming\npm\node_modules\simpler-paper\node_modules\send\index.js:421:12)
    at onstat (C:\xxxxxxxxxxxxx\AppData\Roaming\npm\node_modules\simpler-paper\node_modules\send\index.js:727:26)
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by berubou** [comment]
感谢使用，会尽快修复的

**Comment by unix** [comment]
@berubou 可能是移除 `express` 使用 http 那次 commit 引起的，你看看那次的改动

**Comment by berubou** [comment]
@WittBulter 嗯，晚点看看

**Comment by Tony1952466760** [comment]
同样遇到此问题 ，点击切换就报错

**Comment by berubou** [comment]
#75  已提交，麻烦稍等一下 @Tony1952466760 @liuhangbiao

**Comment by berubou** [comment]
@liuhangbiao @Tony1952466760  done

**Comment by unix** [comment]
注意更新版本至 v0.3.0-beta.4
